pulumi/pulumi-tf-provider-boilerplate

- README.md
This came up in the community chat when @igorshapiro was working on porting the DataDog provider.
> Note Go version requirement in README.md

- README.md
With the [move to Hugo](https://github.com/pulumi/docs/pull/1088), all new package docs will be under `.../pulumi/*` instead of `.../@pulumi/*`. (Older links to existing packages under `@pulumi` will continue to work and redirect.)
> Update API docs link

- CHANGELOG.md
- Makefile
- README.md
I added the `make prepare` command in order to simplify the renaming of the files and its contents. This expect two arguments, `NAME` and `REPOSITORY`.
> Add prepare command to rename the `xyz` occurrences

- resources.go
```shell
$ pulumi-tfgen-github python --overlays overlays/python/ --out sdk/python/
```
was failing with the following error:
```
error: failed to generate package: lower version bound must be at least 0.17.28
```
Not sure when the lower bound was added, but this PR updates the repo to reflect that.
> Update min pulumi version for python

- README.md
We should also update the links in all of the provider repos to link to the resource docs rather than the Node.js docs.
> Update the API docs link to use the resource docs link format

- Makefile
- provider/go.mod
Fixes: #37
We no longer depend on an old binary to help generate the schema and examples - this is taken care of in 2 steps in the schema gen now
> Removing the download plugin step for examples generation

- README.md
Dotnet types cannot contain fields of the same name. Therefore, we need to use the `CSharpName` functionality when generating the provider. This PR adds an example.
> Add dotnet caveat

- CONTRIBUTING.md
Update CONTRIBUTING.md template as quality enhancement to https://github.com/pulumi/home/issues/1779
Redirects to the main contributor guide for the Pulumi ecosystem.
> Update CONTRIBUTING.md template

- README.md
They also expect a package name
Don't tell we need to clone in `$GOPATH`, this is not needed anymore.
> Fix documentation around use of tfbridge.Make* functions

- provider/go.mod
Background
---
Invalid semantic version `v3.24.1.0` results in `require github.com/pulumi/pulumi/sdk/v3: version "v3.24.1.0" invalid: unknown revision v3.24.1.0` -- updated to latest valid version `v3.25.1`
> fix: Use correct version of pulumi v3 sdk in go mod

- Makefile
Background
---
As the Makefile uses bash builtins, e.g. `[[`, `]]` -- explicitly set the shell to bash
Note
---
Although OSX happily defaults to bash, on Ubuntu/Debian it defaults to sh and results in: `/bin/sh: 1: [[: not found`
> fix: Explicity specify bash as shell in Makefile

- Makefile
- README.md
- provider/cmd/pulumi-resource-xyz/.gitignore
- provider/cmd/pulumi-resource-xyz/generate.go
- provider/cmd/pulumi-resource-xyz/main.go
It was brought to my attention that we need to do some house cleaning to have this fully work.
See also: https://github.com/pulumi/home/issues/1765
> Revert "Use go:embed instead of go generate for schema"

- README.md
Add the storyline for third-party provider creation to README. Link to `deployment-templates`'s README instructions for releasing and publishing binaries.
Part of https://github.com/pulumi/home/issues/1997
> Add details for third-party provider creation to README

- deployment-templates/release.yml
The job publish_sdk is referencing a job name using an underscore instead of a dash.
> fix: GitHub action fails due to incorrect job name reference

- deployment-templates/.goreleaser.yml
Plugin binary name should be `pulumi-resource-...`
Signed-off-by: Ringo De Smet <ringo@de-smet.name>
> Fix plugin binary name in template

- .gitignore
- provider/cmd/pulumi-resource-xyz/generate.go
- provider/cmd/pulumi-resource-xyz/main.go
- provider/go.mod
- sdk/go.mod
Also adds an override for tfexec + the change to use go:embed
Fixes: #79
> Upgrade to v3.36.0 of Pulumi

- provider/go.mod
Fixed issue where a previous PR introduced an incorrect version in `provider/go.mod`.
> Corrected version of terraform-plugin-sdk replace in provider/go.mod

- .devcontainer/Dockerfile
- CHANGELOG.md
When running `make build_sck` I was receiving the following:
`A fatal error occurred.  The folder [/usr/share/dotnet/host/fxr] does not exist.`
This change should fix that issue.
https://stackoverflow.com/questions/73753672/a-fatal-error-occurred-the-folder-usr-share-dotnet-host-fxr-does-not-exist
> fix: devcontainer dotnet Dockerfile install

- COPYRIGHT
Fixes #107 
We use XYZ as the demo provider everywhere else, so this uses the same for the copyright statement.
> Change AWS to XYZ in COPYRIGHT

- provider/resources.go
A user hit this issue:
```
error: fatal: failed to Init GRPC to register RPC handlers: failed to create resource provider: ProviderInfo needs a semver-compatible version string, got info.Version=""
```
Bridged providers all seem to have it:
https://github.com/pulumi/pulumi-aws/blob/b5e02e8663502b28cc7bce5c326dc82822b1b718/provider/resources.go#L818C3-L818C37
https://github.com/pulumi/pulumi-gcp/blob/89c9fae772dcd8abc3b4908a203981aa77f8116b/provider/resources.go#L465
> Add version to provider info

- provider/resources.go
The new instructions walk you through how to setup `xyz.New(version.Version)()` at the point where it is used. This will hopefully be clearer to our users.
Fixes https://github.com/pulumi/pulumi-tf-provider-boilerplate/issues/116
Fixes #119
> Improve the instructions for bridging non sdkv2 providers

- .gitignore
should prevent issues like https://github.com/pulumi/pulumi-meraki/issues/1
> Add redundant SDK files to gitignore

- Makefile
Noticed this during a new project :)
It's calling the error message as if it's a command, and I assume this should have been echoed instead.
```
/bin/bash: Project already prepared: command not found
make: *** [prepare] Error 1
```
> Fix: Echo error message

- provider/resources.go
Use a PNG logo. SVG is not accepted by nuget.org for the published SDK package.
> Use a PNG logo.

- README.md
needed when running `make lint_provider`
> add: golangci-lint prerequisite

- provider/resources.go
The example for `PluginDownloadURL` didn't work before adding path to a specific releases downloads.
> Fix `PluginDownloadURL` example path

- .ci-mgmt.yaml
- Makefile
This PR removes the unused field `enableAutoRelease` from `.ci-mgmt.yaml`. [ci-mgmt](https://github.com/pulumi/ci-mgmt) recently started [rejecting](https://github.com/pulumi/ci-mgmt/pull/1126) unknown fields. This does not cause any change to the semantics of `.ci-mgmt.yaml`.
Part of https://github.com/pulumi/ci-mgmt/issues/1147
> Fix ci-mgmt: remove unread field `enableAutoRelease` from `.ci-mgmt.yaml`

- provider/resources.go
This depends on https://github.com/pulumi/pulumi-terraform-bridge/pull/2734 merging for the docs link:
https://pulumi-developer-docs.readthedocs.io/projects/pulumi-terraform-bridge/en/latest/docs/guides/new-pf-provider.html
Fixes #169
> Update bridging instructions after we moved `/pf` to `/v3/pkg/pf`

- setup.sh
Fixes https://github.com/pulumi/pulumi-tf-provider-boilerplate/issues/222, https://github.com/pulumi/pulumi-tf-provider-boilerplate/issues/223
Fix the usage text to align with the actual options the script supports
> Fix usage text in setup.sh

- SETUP.md
> Document cron job for workflow updates
